# Data PreProcessing

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Read the dataset

In [2]:
dataset=pd.read_csv("F:\DL Training--17th Feb\ANN\Churn_Modelling.csv")

In [3]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [4]:
dataset.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [5]:
dataset.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [6]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [7]:
type(dataset)

pandas.core.frame.DataFrame

In [8]:
x=dataset.iloc[:,3:13]#iloc-integer location

In [9]:
x

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [10]:
y=dataset.iloc[:,13]

In [11]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [12]:
type(x)

pandas.core.frame.DataFrame

In [13]:
x=x.values

In [14]:
type(x)

numpy.ndarray

In [15]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [16]:
y=y.values

In [17]:
type(y)

numpy.ndarray

In [18]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [19]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [20]:
x.shape

(10000, 10)

# Encode

In [21]:
from sklearn.preprocessing import LabelEncoder

In [22]:
lb=LabelEncoder()

In [23]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [24]:
x[:,2]=lb.fit_transform(x[:,2])

In [25]:
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [26]:
lb1=LabelEncoder()

In [27]:
x[:,1]=lb1.fit_transform(x[:,1])

In [28]:
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [29]:
from sklearn.preprocessing import OneHotEncoder

In [30]:
from sklearn.compose import ColumnTransformer

In [31]:
ct=ColumnTransformer(transformers=[("oh",OneHotEncoder(),[1])],remainder="passthrough")

In [32]:
x=ct.fit_transform(x)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [33]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [34]:
x[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [35]:
x.shape

(10000, 12)

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2)

In [38]:
x_train.shape

(8000, 12)

# Feature Scaling

In [39]:
from sklearn.preprocessing import MinMaxScaler

In [40]:
sc=MinMaxScaler()

In [41]:
x_train=sc.fit_transform(x_train)

In [42]:
x_train

array([[1.        , 0.        , 0.        , ..., 1.        , 1.        ,
        0.70249754],
       [0.        , 0.        , 1.        , ..., 1.        , 0.        ,
        0.63280788],
       [1.        , 0.        , 0.        , ..., 1.        , 1.        ,
        0.29929548],
       ...,
       [0.        , 0.        , 1.        , ..., 1.        , 0.        ,
        0.69307434],
       [0.        , 0.        , 1.        , ..., 0.        , 1.        ,
        0.78389166],
       [1.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.12640032]])

In [43]:
x_test=sc.transform(x_test)

# Building NN Model

# Import Required packages

In [44]:
import keras

Using TensorFlow backend.


In [45]:
from keras.models import Sequential

In [46]:
from keras.layers import Dense # Dense NN Layer

# Init NN Model

In [75]:
model=Sequential()

In [48]:
model

# Create Structure

# Add input layer

In [49]:
x_train.shape[1]#no of inputs -- no of neurons in input layer

12

In [76]:
model.add(Dense(input_dim=x_train.shape[1],kernel_initializer="random_uniform",activation="relu",units=30))

# Add Hidden Layer

In [77]:
model.add(Dense(kernel_initializer="random_uniform",activation="relu",units=40))

# Add Ouput layer

In [78]:
model.add(Dense(kernel_initializer="random_uniform",activation="sigmoid",units=1))

# Compile the NN Model

In [79]:
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])

In [80]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 30)                390       
_________________________________________________________________
dense_5 (Dense)              (None, 40)                1240      
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 41        
Total params: 1,671
Trainable params: 1,671
Non-trainable params: 0
_________________________________________________________________


# Train the NN Model`

In [81]:
model.fit(x_train,y_train,epochs=100,batch_size=32)

Epoch 1/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.5142 - accuracy: 0.7941
Epoch 2/100
8000/8000 [==============================] - 0s 62us/step - loss: 0.4585 - accuracy: 0.7966
Epoch 3/100
8000/8000 [==============================] - 1s 71us/step - loss: 0.4414 - accuracy: 0.8081
Epoch 4/100
8000/8000 [==============================] - 1s 83us/step - loss: 0.4297 - accuracy: 0.8142
Epoch 5/100
8000/8000 [==============================] - 0s 62us/step - loss: 0.4245 - accuracy: 0.8161
Epoch 6/100
8000/8000 [==============================] - 0s 59us/step - loss: 0.4196 - accuracy: 0.8198
Epoch 7/100
8000/8000 [==============================] - 0s 58us/step - loss: 0.4145 - accuracy: 0.8241
Epoch 8/100
8000/8000 [==============================] - 0s 61us/step - loss: 0.4114 - accuracy: 0.8264
Epoch 9/100
8000/8000 [==============================] - 1s 73us/step - loss: 0.4093 - accuracy: 0.8288
Epoch 10/100
8000/8000 [==============================] - 1s 69

8000/8000 [==============================] - 1s 76us/step - loss: 0.3234 - accuracy: 0.8646
Epoch 80/100
8000/8000 [==============================] - 1s 75us/step - loss: 0.3222 - accuracy: 0.8659
Epoch 81/100
8000/8000 [==============================] - 0s 62us/step - loss: 0.3216 - accuracy: 0.8650
Epoch 82/100
8000/8000 [==============================] - 0s 62us/step - loss: 0.3220 - accuracy: 0.8668
Epoch 83/100
8000/8000 [==============================] - 0s 62us/step - loss: 0.3222 - accuracy: 0.8660
Epoch 84/100
8000/8000 [==============================] - 1s 65us/step - loss: 0.3255 - accuracy: 0.8654
Epoch 85/100
8000/8000 [==============================] - 0s 61us/step - loss: 0.3234 - accuracy: 0.8655
Epoch 86/100
8000/8000 [==============================] - 1s 68us/step - loss: 0.3205 - accuracy: 0.8661
Epoch 87/100
8000/8000 [==============================] - 1s 79us/step - loss: 0.3227 - accuracy: 0.8673
Epoch 88/100
8000/8000 [==============================] - 1s 72us/st

In [82]:
model

# Prediction or Testing the model

In [83]:
y_pred=model.predict(x_test)

In [84]:
y_pred

array([[0.12191764],
       [0.21986717],
       [0.01876014],
       ...,
       [0.02219877],
       [0.1520614 ],
       [0.04828364]], dtype=float32)

In [85]:
y_pred=y_pred>0.5

In [86]:
y_pred#Predicted values

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [87]:
y_test#actual values

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [88]:
from sklearn.metrics import accuracy_score

In [89]:
print("Testing Accuracy Score:",accuracy_score(y_test,y_pred)*100," %")#New data

Testing Accuracy Score: 86.6  %


In [90]:
bank_cus=np.array([[1.0, 0.0, 0.0,665,1,25,2,20000,2,1,1,50000]])

In [91]:
y_pred_cus=model.predict(sc.transform(bank_cus))

In [92]:
y_pred_cus

array([[0.00684368]], dtype=float32)

In [93]:
y_pred_cus>0.5

array([[False]])

# Save the NN Model

In [94]:
model.save("bank.h5")

# Save the scaler object

In [72]:
from sklearn.externals import joblib

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [73]:
joblib.dump(sc,"bank_scaler.save")

['bank_scaler.save']